# Generated by Django 5.2.4 on 2025-07-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, help_text="e.g., '30% OFF'", max_length=50, null=True),
        ),
    ]
