# Generated by Django 5.2.4 on 2025-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_deal_of_the_day_product_offer'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
