# Generated by Django 5.2.4 on 2025-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=50)),
                ("quality", models.CharField(max_length=100)),
                ("expiry", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("isLowStock", models.BooleanField(default=False)),
            ],
        ),
    ]
