# Generated by Django 5.2.4 on 2025-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="barterValue",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(default="In Stock", max_length=50),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(default="kg", max_length=20),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="expiry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="price",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quality",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
