# Generated by Django 5.2.4 on 2025-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('delivery_time', models.CharField(default='30-45 mins', max_length=50)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
